name: CI/CD for Serverless Python Demo

# This workflow will automatically build, test, and deploy the application to AWS
# every time a new change is committed to the main or staging branch.
# It will also run a linter and a test on the application every time a merge request is made to the repository.

on:
  # Trigger the workflow whenever a new change is pushed to the main or staging branch
  push:
    branches:
      - main
      - staging

  # Trigger the workflow whenever a new merge request is made to the repository
  pull_request:
    branches:
      - main
      - staging

jobs:
  # Build the application.
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v2

      # Install the AWS CLI and AWS SAM CLI.
      - name: Install AWS CLI and SAM CLI
        run: |
          sudo apt-get install awscli
          pip install aws-sam-cli

      # Creates a virtual environment and dependencies////////////
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Installing the application dependencies.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Building the app using sam build --use-container.
      - name: Build application
        run: |
          sam build --use-container

  # This job will run the tests.
  test:
    runs-on: ubuntu-latest
    steps:
      # Checking out the code from the repository.
      - uses: actions/checkout@v2

      # Installing the AWS CLI and AWS SAM CLI.
      - name: Install AWS CLI and SAM CLI
        run: |
          sudo apt-get install awscli
          pip install aws-sam-cli

      # Createing a virtual environment and install the application dependencies.
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Runing tests
      - name: Run tests
        run: |
          pytest

  # Deploy the application to AWS.
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      # check out the code from the repository.
      - uses: actions/checkout@v2

      - name: Install AWS CLI and SAM CLI
        run: |
          sudo apt-get install awscli
          pip install aws-sam-cli

      # Deploy the app using sam deploy --guided.
      - name: Deploy application
        run: |
          sam deploy --guided
